### ISSUE TITLE
SSR Apps and using custom traces - nuxt3 

### ISSUE THREAD

**Issue by JulianMar** [bugsnag/bugsnag-js-performance#288]
### Describe the bug
Using the performance library is hard in SSR Apps. In SSR Apps, code can be executed on the server or on the client.
This library is only for the Client and in nuxt we can create a plugin which is only executed on the client side. 
So far so good.

The Problem now happens with the actual components. If we want to create a simple component with two button which start and end a span we run into some problems. As we are executing this code first on the server side, the document is undefined and the performance library will throw an error. We can't execute the code just on the client side, because the document is requested already in the import. As far as I know there is no way to do a conditional import in JS.

Can you guide me here a little bit? I'm not really sure if it's even a bug or the behaviour is wanted like that.

BTW I am the author of [this](https://github.com/JulianMar/nuxt-bugsnag) library and wanted to add this cool feature to make it easy to get started with it :)
 

### Steps to reproduce
Reproduction here: 

Just refresh the page and you know what I mean

### Environment
* BugSnag Performance library version: 1.0.0
* BugSnag Error Monitoring library version (if any): -
* Browser framework version (if any):
    * Nuxt: 3.6.5

### Example Repo 

- [x] Link to it here: https://stackblitz.com/edit/nuxt-starter-wljh1k?file=app.vue

**Comment by grez96** [comment]
Same issue using Next.JS

`ReferenceError: document is not defined`

**Comment by mclack** [comment]
Hi @JulianMar

We’re glad to hear you’re interested in using our Performance library!

Our engineers will look into this and we will make sure to update the thread with any updates, or ask any questions if we need to. Thanks!

**Comment by clr182** [comment]
Hi :wave: 

🎉 🎉 🎉   We have just released a new version [(v2.2.0)](https://github.com/bugsnag/bugsnag-js-performance/releases/tag/v2.2.0) of the Bugsnag-js-performance notifier that has support for SSR apps and using custom traces! 

If after update updating you see any issues then please let us know and we can investigate further.
