### ISSUE TITLE
on react-native, debugger is not working after installing @bugsnag/react-native-performance

### ISSUE THREAD

**Issue by withel21** [bugsnag/bugsnag-js-performance#370]
![image](https://github.com/bugsnag/bugsnag-js-performance/assets/20988821/0556ee6a-eed5-43d5-a91f-9ef8eb2f4376)

After installing @bugsnag/react-native-performance, I can see this image when turning on chrome debugger.

So I've inspect the installed codes and found `getDeviceInfo` is the synchronous method.
(My team uses old architecture of react-native)

And I found the documents([ios](https://reactnative.dev/docs/native-modules-ios#synchronous-methods), [android](https://reactnative.dev/docs/native-modules-android?android-language=java#synchronous-methods)) said synchronous method doesn't work with chrome debugger.

Is there any side step or plan to resolve this?

Thank you.

**Comment by clr182** [comment]
Hi @withel21 
We do have an item on our backlog aimed at investigating handled errors from the React Native debugger. We will be sure to keep you informed of any updates.

**Comment by RobertoSmartBear** [comment]
This feature request has been released in v[2.7.0](https://github.com/bugsnag/bugsnag-js-performance/releases/tag/v2.7.0)
