### ISSUE TITLE
React router v5

### ISSUE THREAD

**Issue by tasawar-hussain** [bugsnag/bugsnag-js-performance#397]
The [current example](https://docs.bugsnag.com/performance/integration-guides/web/customizing-routes/#react-router) in docs is for react-router v6. Does this package work with react-router v5, if yes, an example would be great.

**Comment by clr182** [comment]
Hi @tasawar-hussain,

Unfortunately, without non-arbitrary work the performance js library does not support react-router v5. The library currently uses `matchPath` internally and the upgrade from v5 to v6 of the react-router changes the order of arguments. 

Furthermore the react-router v5 tended to have routes defined all over the application component tree and provided no way of getting the full list of routes, which is needed for any routing provider implementation.

I'm going to close this out as something we will not be implementing, however please feel free to reopen this issue if you have any further information to share.
