### ISSUE TITLE
plugin-react-navigation-performance does not exists in npm/yarn registery.

### ISSUE THREAD

**Issue by ahoseinian** [bugsnag/bugsnag-js-performance#402]
### Describe the bug
as per describe in the [performance library docs](https://docs.bugsnag.com/performance/integration-guides/react-native/navigation-libraries/). i have Tried to install the plugin-react-navigation-performance but this plugin doesn't seem to be in [registery](https://www.npmjs.com/search?q=%40bugsnag%2Fplugin-react-navigation-performance) or in this repo anymore.

also this package https://github.com/bugsnag/bugsnag-js-performance/tree/next/packages/react-navigation installation instructions seems to be old or wrong since this path `@bugsnag/react-navigation-performance/native` does not exists at all. 

### Steps to reproduce
1. Go to [docs](https://docs.bugsnag.com/performance/integration-guides/react-native/navigation-libraries/)
2. try to install the navigation plugin
3. See error

### Environment
* React-Native

**Comment by gingerbenw** [comment]
Thanks @ahoseinian,

We made a few changes to the package naming convention during the development process and it appears I missed some documentation updates!

Could you please try

`npm install @bugsnag/react-navigation-performance`

and

`import { ReactNavigationNativePlugin } from '@bugsnag/react-navigation-performance'`

Hope this helps!

**Comment by ahoseinian** [comment]
hi @gingerbenw,

Thanks for the response. I have actually tried that as well but got some errors. and since the docs are outdated I was not sure if I am doing the right thing. I will explain what I did

first, I did something like
```
const navigationPlugin = new ReactNavigationNativePlugin();
BugsnagPerformance.start({
  apiKey: '......',
  plugins: [navigationPlugin],
});

const NavigationContainerBugsnag = navigationPlugin.createNavigationContainer();
```
but the plugin is not configured like this somehow and I get this [error](https://github.com/bugsnag/bugsnag-js-performance/blob/a65f200b7a65f9abdcaa9a0e92d1d9d3434e4c54/packages/react-navigation/lib/react-navigation-native-plugin.ts#L14).

second, I tried using `BugsnagPerformance.getPlugin( ReactNavigationNativePlugin )`. but it also returns undefined.

**Comment by gingerbenw** [comment]
Thanks for the update @ahoseinian!

Are you calling `createNavigationContainer` after calling start? This error usually occurs when Bugsnag has not been started when you call the plugin methods.

**Comment by mclack** [comment]
Hi @ahoseinian 

As there hasn't been any activity here for a while, we are now closing this issue.

If you continue to experience any problems, please feel free to reopen this issue and provide any additional relevant information (such as whether you are calling `createNavigationContainer` after start), or open a ticket with us directly by contacting [support@bugsnag.com](mailto:support@bugsnag.com).
