### ISSUE TITLE
I got issue in Conflicting peer dependency in react native project.

### ISSUE THREAD

**Issue by Karthik-V26** [bugsnag/bugsnag-js-performance#405]
<img width="902" alt="Screenshot 2024-02-13 at 5 04 02 PM" src="https://github.com/bugsnag/bugsnag-js-performance/assets/82167049/9c371327-0651-47ce-b6ff-d0c205b2fd10">

### Bug description
I got issue in Conflicting peer dependency of @react-native-community/netinfo.
I am using a newer version @react-native-community/netinfo@11.2.1
how can I solve this confict.  Atteched a image for reference.

### Environment
* BugSnag Performance library version: "^2.1.0",
Using in react native project.

**Comment by mclack** [comment]
Hi @Karthik-V26 

Thanks for raising this. We've added a task to our backlog for `@bugsnag/react-native-performance` to allow newer versions of the `@react-native-community/netinfo` package in the dependencies. We will make sure to update this thread as soon as this change has been made.

In the meantime, would you be able to remove `v11.2.1` of the `netinfo` package and use the older version? This should fix the peer dependency conflict while we look to resolve this.

**Comment by mclack** [comment]
Hi @Karthik-V26 

I just wanted to let you know that this peer dependency conflict has now been resolved as of `bugsnag-js-performance` v2.3.0: https://github.com/bugsnag/bugsnag-js-performance/releases/tag/v2.3.0

Thanks again for raising this with us. Please let us know if you continue to notice any issues.
