### ISSUE TITLE
Named export 'isCuid' not found. The requested module '@bugsnag/cuid' is a CommonJS module

### ISSUE THREAD

**Issue by ondrejsevcik** [bugsnag/bugsnag-js-performance#441]
### Describe the bug
When `@bugsnag/browser-performance` package is imported in Vitest, it fails with the following error.

```
Error: SyntaxError: Named export 'isCuid' not found. The requested module '@bugsnag/cuid' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@bugsnag/cuid';
const { isCuid } = pkg;
```

### Environment
* BugSnag Performance library version: 2.4.1
* BugSnag Error Monitoring library version (if any): 2.4.1
* Node.js: v20.9.0

---

I could send out PR fixing the import style if you're open to external PR contributors.

**Comment by toniewypada** [comment]
Hi 👋🏻, our dev team is working on implementing a fix for this. We'll let you know about any updates!
