### ISSUE TITLE
Vue router path dynamic param with empty parenthesis doesn't match corresponding url

### ISSUE THREAD

**Issue by thomaspaillot** [bugsnag/bugsnag-js-performance#460]
### Describe the bug
Vue router route path can contain parenthesis at the end of a dynamic param like this /:projects()/all and when you use path-to-regexp to match a potential url the regex generated by path-to-regexp doesn't work because of the parenthesis.

### Steps to reproduce
```
import pathToRegexp from 'path-to-regexp';

'/my-project-name/all'.match(pathToRegexp('/:projects()/all')) // return false
'/my-project-name/all'.match(pathToRegexp('/:projects(\\S+)/all')) // return true
'/my-project-name/all'.match(pathToRegexp('/:projects/all')) // return true
````

### Environment
* BugSnag Performance library version: 2.6.0
* BugSnag Vue Router Performance library version: 2.4.0
* Browser framework version (if any):
    * Vue: 3.4.27

### Example Repo

[Reproduction](https://codesandbox.io/p/sandbox/lucid-lalande-vanilla?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxbytbre00063b6i06kzsxv1%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxbytbre00023b6iyiqri9u6%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxbytbre00033b6iqviiliyv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxbytbre00053b6inl3uwhpt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxbytbre00023b6iyiqri9u6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxbytbre00013b6i77rxgkpn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.html%2522%257D%255D%252C%2522id%2522%253A%2522clxbytbre00023b6iyiqri9u6%2522%252C%2522activeTabId%2522%253A%2522clxbytbre00013b6i77rxgkpn%2522%257D%252C%2522clxbytbre00053b6inl3uwhpt%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxbytbre00043b6ixp26ca5f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxbytbre00053b6inl3uwhpt%2522%252C%2522activeTabId%2522%253A%2522clxbytbre00043b6ixp26ca5f%2522%257D%252C%2522clxbytbre00033b6iqviiliyv%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxbytbre00033b6iqviiliyv%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) 

### Possible fix

I tried to use `createRouterMatcher` function from vue-router and it seems to works (I didn't flatten the routes as getRoutes() was already a flat array in my case):

```
import { START_LOCATION, createRouterMatcher } from 'vue-router';

const matcher = createRouterMatcher(router.getRoutes(), { strict: false, sensitive: false });

function resolveRoute(url) {
  try {
    const location = matcher.resolve({ path: url.pathname }, START_LOCATION);
    return location.matched.length > 0 ? location.matched[0].path : 'no-route-found';
  } catch (err) {
    return 'no-route-found';
  }
}
```

**Comment by clr182** [comment]
Hi @thomaspaillot 

By default, path-to-regexp does not handle paths with parentheses unless they are properly escaped or used in a way that the library expects.

Sanitizing your paths with the use of escape characters is the recommended approach to handling pattern matches on params for `pathToRegexp` 

Alternatively you could implement some custom parsing logic if the use of special characters are unavoidable.

```
const projectId = encodeURIComponent('/:projects()/all');
this.$router.push(`/projects/${projectId}/all`);
```

**Comment by thomaspaillot** [comment]
It's Nuxt that is generating the path automatically so I cannot change this unfortunately. I use my custom provider if you're not willing to change this but keep in mind that this affects all Nuxt users.

**Comment by mclack** [comment]
Hi @thomaspaillot 

We've added a task to our backlog to investigate this further and consider solutions. We'll make sure to post any updates on this thread.

**Comment by clr182** [comment]
Hi @thomaspaillot 

I'm just reaching out to let you know that we have release a new version of the [BugSnag JS Performance SDK (v2.8.0)](https://github.com/bugsnag/bugsnag-js-performance/releases/tag/v2.8.0) which should solve the vue router issue you are facing. 
If you are still receiving this same issue after updating to the latest version, please let us know and we can investigate further.

**Comment by thomaspaillot** [comment]
Thanks for this new release, I'll upgrade and replace my custom provider and let you know if it's not working but I took a look at your implementation and it's quite similar to what I did in my custom provider so hopefully it shoud work.
